### ISSUE TITLE
Native barcoding of samples

### ISSUE THREAD

**Issue by wdecoster** [LooseLab/ru#23]
Hi, me again! I figured this question might be of interest for multiple users so I ask it here... 
Is there something we have to take into account when we use (native) barcoding on samples prior to read until?

Is this something you tried?
Naively I would expect the barcodes don't align to any target, but we should quickly enough have enough unique sequence to enable a decision...

Eventually, we might want to balance out the coverage of the barcodes with read until, but right now we'll assume that our lab-fu is good enough to get some equimolar pooling right.

Cheers,
Wouter

**Comment by mattloose** [comment]
Hello again!

As you say, native barcodes won't align to the reference (or they shouldn't do anyway ;-) so all that will happen is your alignments will take a little longer - you may find your mean rejected read lengths end up being a little longer.

With respect to balancing barcodes - we haven't tried this yet using this approach, but it would be relatively straightforward to integrate.

I'm sure the lab-fu will sort you out!

Matt

**Comment by wdecoster** [comment]
Alrighty, exciting times!

**Comment by joanmarticarreras** [comment]
Hi!

I have a similar question regarding the interaction between RU and a barcoded library. Will RU start filtering reads before or after sorting the barcode?

Joan

**Comment by mattloose** [comment]
Right now readfish isn't barcode aware - so it will simply ignore the barcodes and process the data as if they were not barcoded. This is something we intend to add in soon to make samples barcode aware. But at present you can't say selec region a from barcode 1 and region b from barcode 2.

**Comment by joanmarticarreras** [comment]
Thanks Matt!

Mostly I was thinking on using several samples (with different % of target genome vs host) at the same time using the NBD kit. 

Let's say we have 4 samples, deferentially spiked with a target genome as A: 5% target spike, B: 1%, C: 0.5%, D: 0,05%. Once the run has started, readfish target is launched with a minimap2 index for our target genome. Then I may suppose that RU will enrich the run with my spikes regardless of the barcode. Based on this set-up, is it possible that in sample D no (or little) reads are recovered for the target genome?

**Comment by mattloose** [comment]
Yes - so I would expect the behaviour here to be that readfish (ru) would enrich the run regardless of barcode. This is a neat experiment and I'd be quite interested to know the answer. They dynamics are interesting to think about - your analysis will need to be quite nuanced.

So - I'd expect you to see some level of enrichment across each of the barcodes, but your rejection rates will obviously be a  lot higher in sample D. Depending on what you mean by 0.05% you will be rejecting 1999 reads for every read you want to sequence. If your reads are short then you won't see a miraculous increase in your target - but you will get more than if you were not running read until.

You could play some fun analysis tricks here - I'd be tempted to specify that a barcode was reported at each end of your read. By definition this would only report the reads that were fully sequenced - so all your rejected reads would end up as being unclassified and just your sequenced reads would end up in barcodes. 

Do let me know if you try this out for real!
