### ISSUE TITLE
Guppy_CPU support?

### ISSUE THREAD

**Issue by jelber2** [LooseLab/ru#25]
Hi,

I was wondering if about using `ru` without a GPU. Our Server has 40 cores (80 threads), so I think we might be able to use `ont-guppy-cpu_3.4.1_linux64.tar.gz` as it comes with `ont-guppy-cpu/bin/guppy_basecall_server`.

Any idea if `guppy_basecall_server` could keep up with a MinION using CPUs?

**Comment by alexomics** [comment]
The CPU base call server should be compatible, but we haven't tested it.

**Comment by jelber2** [comment]
@alexomics thank you for the quick response. We might give this a try!

**Comment by iiSeymour** [comment]
Pyguppyclient works just fine with guppy_basecall_server using the CPU.

I expect a 40 core CPU to keep up with a MinION, you can use either the guppy client or the example client in pyguppyclient to check how many samples/s you can get on a batch of example reads. For a MinION you will want to be seeing ~1.8E6 samples a second. Use `htop` to check all cores are being used.

**Comment by mattloose** [comment]
So I suspect you can use far less CPU than 40 to keep up as long as the chunk size is small. A trick here is to configure the maximum number of chunks that you look at to be small - say no more than 4 chunks with a chunk size of 0.4s. This sacrifices a little - any read that you cannot identify within 1.6 seconds will be unblocked and so you may unblock a few reads you wanted - but you still see enrichment. 

It's worth keeping an eye on how long it takes to process a single batch of reads though. If that number climbs above your chunk size you can end up in difficult (i.e if it takes 1 second to process 0.4 seconds worth of data...). We've found this can happen right at the start of a run when you first connect to MinKNOW - you instantly get a batch of reads containing 400plus reads. This takes a long time to process and you have a big back log. If this happens, briefly pausing the run, waiting for all the reads to finish processing and then unpausing the run gives you nice small batches again and you are off. 

So - my point really is that I think this can be otpimised to work on far fewer than 40 cores!
