### ISSUE TITLE
ReadUntil for filling in gaps?

### ISSUE THREAD

**Issue by jelber2** [LooseLab/ru#26]
Not really an issue, rather a question. Curious what others think about the idea of using ReadUntil with one MinION flowcell and some hopefully long Nanopore reads (N50 > 50 Kbp) to try and fill in gaps in a several Mbp region that was scaffolded with Hi-C reads but still has some gaps of unknown sizes (arbitrary 1000-bp gaps between contigs joined by Hi-C contact maps). It seems like one could use the desired region as the reference for ReadUntil and then use Racon to fill in gaps with the obtained enriched reads. Any thoughts?

**Comment by mattloose** [comment]
As you say this isn't really issue and is a question. This is an obvious application and one I am sure people will be working. To discuss this further it would be better moved to a forum like the nanopore community.
