### ISSUE TITLE
counter intuitive result

### ISSUE THREAD

**Issue by TorHou** [LooseLab/ru#34]
We have simulated a run that we would like to do based on your bulk file. But we get really counter-intuitive results. 
The toml we have used is built like this:
```
[caller_settings]
config_name = "dna_r9.4.1_450bps_fast"
host = "localhost"
port = 5550
​
[conditions]
reference = "some.mmi"
axis = 1
​
[conditions.0]
name = "control"
control = true
min_chunks = 0
max_chunks = 4
targets = ["p"]
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"
​
[conditions.1]
name = "enrich_t1"
control = false
min_chunks = 0
max_chunks = 4
targets = ["t1"]
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"
​
[conditions.2]
name = "enrich_ts"
control = false
min_chunks = 0
max_chunks = 4
targets = ["t1","t2","t3","t4","t5","t6"]
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"
​
[conditions.3]
name = "deplete_ts"
control = false
min_chunks = 0
max_chunks = 4
targets = ["t1","t2","t3","t4","t5","t6"]
single_on = "unblock"
multi_on = "unblock"
single_off = "stop_receiving"
multi_off = "stop_receiving"
no_seq = "proceed"
no_map = "proceed"
```

Afterwards I split the fastq according to the channel in each reads header with something like the following:
```
run_info, conditions, reference, caller_settings = get_run_info(toml_file)
channel = int(fastq_header.split()[4].split("=")[1])
field = run_info[channel]
```

After I utilized summarise_fq.py on each conditions fastq and looked at the sum column as a proxy for whether the enrichment has worked or not. 
And I see:
```
Conditions:               0        1        2         3
description:              control  t1_enr   ts_enr    ts_depl
Total bases in ts:        334294   30561    7069      1210683
Normalized:               1        0.091    0.021     3.622
```
So it's the complete opposite of what I expected. Do you have an idea of what I am doing wrong ?

**Comment by mattloose** [comment]
Hi,

I think the sum column isn't as helpful as you think when using a bulk file. If a read is "rejected" in bulk playback, it doesn't actually get rejected - it simply gets split into smaller fragments. This is because the underlying signal through the flowcell doesn't change.

So - the way we measure efficiency of read until when running playback is to look at the length distributions for reads on and off target. We expect reads that originate from a region we are rejecting from will be shorter than those originating from regions of interest. 

I hope that helps.

**Comment by TorHou** [comment]
Yes, thank you. We will try a simpler approach and run it on a Flongle to get some more experience with read until.
