### ISSUE TITLE
Playback own fast5

### ISSUE THREAD

**Issue by ythuang0522** [LooseLab/ru#36]
Dear RU authors,

Thanks to the well-written documents, we ran the simulation using the provided fast5 quite well. 
However, we couldn't apply the simulation protocol on our own sequence fast5 generated by MinKnow (19.12.5, GridIon).
We found the internal formats of your fast5 quite different from those generated by MinKnow (multiple fast5 per run and no channel groups while your have a single fast5 and channel groups).
Is any way we can run simulation using our previous runs?

Thanks,
Yao-Ting

**Comment by mattloose** [comment]
Hi

How did you generate your bulkfile? Which settings did you use? It sounds as though you are trying to use a standard fast5 file output for basecalling and not a bulkfile here? Can you share the name of your fast5 file?

Thanks.

**Comment by ythuang0522** [comment]
We overlooked a didn't turn on the bulk fast5 output. Indeed those are standard fast5 not in bulk format. Seems no way to simulate old samples. Thanks for clarification.

**Comment by 2387882242** [comment]
Hi Matt, 

I saved my own bulk file when I sequencing with flongle, and the file name is something like "ACL415_2d19df4d_0.fast5". 
The playback with your bulk fast5 was OK, but I get an "Script failed ..." error when I use my bulk file for a playback experiment.

Where's the problem? I hope I can get your advice.

**Comment by DanteV19** [comment]
Dear RU authors,

Just like @ythuang0522 I could run the simulation using the provided fast5 quite well.
However, I couldn't apply the simulation protocol on my own bulk? fast5 file generated by MinKnow (24.02.19, PromethION).
Even though I selected the advanced options for bulk in MinKNOW.
I also noticed the same difference in the internal formats of the fast5 files (multiple fast5 per run and no channel groups while you have a single fast5 and channel groups).

Used setting were:
![IMG-20240909-WA0003](https://github.com/user-attachments/assets/42209c32-6249-4aa1-bbe1-7d9f43c1a3de)

![IMG-20240909-WA0002](https://github.com/user-attachments/assets/35ecb7ec-84e3-4b6c-b476-9f9f4f99b35c)


Name of my fast5 file: PAY00003_pass_7479b0ee_c5208e21_0.fast5

In which way have you created your bulk fast5 file? And if it was not directly created from the sequencing device, what modifications did you perform on the sequencing output to create your bulk file?

Thanks in advance,

Dante

**Comment by mattloose** [comment]
Hi,

The file you are passing to minknow is not a bulk fast5 file, it is a read file. These are not the same thing. 

To generate a bulkfile you have to use the advanced options on the output settings:
![image](https://github.com/user-attachments/assets/cbbb45d1-bd26-4ba6-afe6-f12e805d25bf)

and configure the bulkfile to save with raw data as shown here.

Hope that helps.

**Comment by DanteV19** [comment]
Thanks for your very quick response. Good to know the correct settings to make a bulk file.
However, since I cannot use the sequencing device again anytime soon, is there a way to merge the read files that I have now that were generated by selecting the advanced bulk settings: Events, Read table and Raw?

Thanks in advance

**Comment by mattloose** [comment]
Unfortunately not that I know of currently.

**Comment by DanteV19** [comment]
If I were to run the sequence device with the settings you have shown, regardless of all other settings, should I still expect a working bulk file for playback? And will it generate just one bulk file or multiple? And what is the reason that Events has to be unselected?

Thanks in advance

**Comment by DanteV19** [comment]
I noticed that for raw reads ouput ".POD" was selected. But the provided bulk file is in fast5. Can bulk pod5 files also work for playback?

**Comment by mattloose** [comment]
It's a little confusing but the raw output is referring to the read files not the bulk file. As I understand it right now the bulk file is still fast5 only.

**Comment by DanteV19** [comment]
I thought the selected option for "Raw reads output" would also affect the bulk file format. But as I understand from your response the bulk file will always be fast5.
When we generated sequencing data with the bulk option selected the bulk file seemed to be missing.
So, I have some more questions about the bulk file.
Whenever the bulk option is selected, at which relative path within the configured "Saved output file location" should I expect the bulk file to be generated and how should the name of the bulk file look like?
Is it possible that newer MinKNOW versions or a PromethION sequencing device may not be able to generate a bulk file even if there is a bulk option?

Thanks in advance

**Comment by mattloose** [comment]
If your data are written to:

/data/my_experiment/my_sample/

then your raw bulk fast5 file will be in /data/

Does that help?

As far as I am aware minknow is still writing out bulk fast5 files.

**Comment by DanteV19** [comment]
Yeah, that helps. Thanks for the confirmation.
