### ISSUE TITLE
Manager Sending reset : human error ?

### ISSUE THREAD

**Issue by svennd** [LooseLab/ru#38]
In our latest run, we noticed that read until script stopped with the following message : 
```2020-04-13 11:18:33,073 Manager Sending reset
2020-04-13 11:18:33,073 read_until_api_v2.main Reset request received, shutting down...
2020-04-13 11:18:33,086 read_until_api_v2.main Reset signal received by action handler.
2020-04-13 11:18:33,151 read_until_api_v2.main Stopping processing of reads due to reset.
2020-04-13 11:18:33,338 read_until_api_v2.main Stream handler exited successfully.
2020-04-13 11:18:33,395 ru.ru_gen Finished analysis of reads as client stopped.
2020-04-13 11:18:33,543 Manager Worker exited successfully.
```
The sequencing continued; but read until, for some reason stopped "randomly". This is the second time. The first time we thought it was a human error; but now, during that time, there was nobody around the machine ... 

What can causes the script to exit ? We run _ru_generators_ in a Linux screen (if that should be relevant)

thanks;

**Comment by alexomics** [comment]
How long was your sequencing run configured for? Currently the default read until run time (given by the `--run-time` parameter, in seconds) is 172800 (48 hours).

**Comment by mattloose** [comment]
Hah - was just about to ask the same question as @alexomics - can you provide your exact run command and the toml file as well? Thanks

**Comment by svennd** [comment]
Hey, 

Thanks for the fast answer :) So to resolve this issue add : --run-time 259200 (72h) ? can we set it up it keeps running until killed ?

for reference : 

The ru command : 

```
ru_generators --device $device_id --experiment-name "after_power" --toml /data/read_untill_setup/20200409_207112_Read_Until_MinION_Test_2.toml --log-file /data/read_untill_setup/20200409_207112_Read_Until_MinION_Test_2_after_power.log
```
Toml file : 

```
[caller_settings]
config_name = "dna_r9.4.1_450bps_hac"
host = "127.0.0.1"
port = 5556

[conditions]
reference = "/data/read_untill_setup/minimap2.mmi"

[conditions.0]
name = "target1"
control = false
min_chunks = 0
max_chunks = inf
targets = "/data/read_untill_setup/target2.txt"
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"
```

**Comment by mattloose** [comment]
Yes - if the client is stopping at 48 hours that will be the issue - set it up with the run-time flag as you say and it will keep going until killed.

You could just set that to an arbitrarily high number but you don't want clients hanging around connected to MinKNOW after a run is done.

As a general point, I would be interested in knowing if you were still generating data from a flowcell after 72 hours when you had read until running - in our experience the flowcell benefits from the run stopping and flushing of the flowcell to load fresh library. I'd expect you to be getting very little valuable data at this point?

**Comment by svennd** [comment]
Not much was coming out at that point, this was after a prolonged weekend so we kept it running; In our tests, we pauze the run and re-add the library; this seems to boost the performance enough (?). But if we continue to do this, we should extend the runtime for this script :) a human error after all; thanks for the support !

**Comment by mattloose** [comment]
You will get better performance if you flush the flowcell and add more library rather than just topping up with extra library. The pores can get blocked as you are rejecting reads and so the flush will give you extra sequencing capacity over the life of the flowcell.

**Comment by wdecoster** [comment]
Oh but we're flushing :)

**Comment by HJTsai** [comment]
> You will get better performance if you flush the flowcell and add more library rather than just topping up with extra library. The pores can get blocked as you are rejecting reads and so the flush will give you extra sequencing capacity over the life of the flowcell.

Hi, 

What's the mean of loading additional library? Do we need to prepare a new fresh library or reuse the previous library sample at the beginning?

Hui-Ju

**Comment by mattloose** [comment]
You need to look at the DNA clear protocols on the Nanopore website. Essentially you can digest away library that is blocking pores and then and additional library to your flowcell. This can be library left over from your first library (we often have material left) or it can be a completely fresh library. Hope this helps.

**Comment by HJTsai** [comment]
> You need to look at the DNA clear protocols on the Nanopore website. Essentially you can digest away library that is blocking pores and then and additional library to your flowcell. This can be library left over from your first library (we often have material left) or it can be a completely fresh library. Hope this helps.

How to store the library left over from our first library?

**Comment by mattloose** [comment]
As above - please check on the ONT sites for support with library preps and protocols - we store left over library in the fridge for several days without a problem.
