### ISSUE TITLE
Read Until on a flongle

### ISSUE THREAD

**Issue by SamMcGreig** [LooseLab/ru#40]
Hello, 

I have managed to set up read until on a our laptop (12 threads), with the aim of running read until on flongles. As I believe less data is generated at once, the hope is that our laptop will be able to keep up. In order to simulate a flongle, would it just be a case of adjusting the `--channels` in the ru_generator command? I've set this to 128 below, but I think it should be 126 to represent a flongle.

If you can suggest any optimisations then I'd be very grateful.

Guppy server command:
`Downloads/ont-guppy-cpu/bin/guppy_basecall_server --config /Downloads/ont-guppy-cpu/data/dna_r9.4.1_450bps_fast.cfg --port 5556 --log_path /ReadUnti
l/read_until/Guppy_server/log.txt --ipc_threads 1 --max_queued_reads 1000 --num_callers 2 --cpu_threads_per_caller 3`

ru_generator command:
`ru_generators --device MN16259 --experiment-name "rut2" --toml human_chr_selection.toml --log-file rut2.log --log-level info --workers 4 --channels 1 128`

I have modified break_reads_after_seconds to be 0.4 and max_chunks to 4.

The current output I'm getting from ru_generators looks okay so far:
2020-04-21 09:56:12,943 ru.ru_gen 9R/0.14979s
2020-04-21 09:56:12,993 ru.ru_gen 4R/0.08269s
2020-04-21 09:56:13,146 ru.ru_gen 3R/0.10329s
2020-04-21 09:56:13,265 ru.ru_gen 5R/0.11896s

How it looks after ~30 minutes.
![ru](https://user-images.githubusercontent.com/17768776/79847315-75fd2680-83b7-11ea-91b4-b04358ec559a.jpeg)

**Comment by mattloose** [comment]
Hi Sam,

Use case on flongle is interesting - you are doing roughly the right thing but I'm going to make some suggestions. 

1. The workers flag doesn't help you at present - this is legacy and you can just ignore it and run on a single thread. The heavy lifting here is done by guppy!
2. You are correct - it should be 126 channels and not 128 for a flongle.
3. I presume you are using our bulk file - this means that the total data will come from 512 channels and so you need to parse out the results from channels 1-128 and compare with the rest of the flowcell to see what's actually happening.
4. Can you share the toml file you used - it looks to me as though it is the same as our original  - it should be selecting chromosome 21 and 22 only. To look at this on playback we plot the mean read length of reads mapped to each chromosome - you should see a difference on channels 1-128 compared with the rest of the flowcell.

Performance wise, you may find that the chunk size setting of 0.4 is not helping you with the CPU basecaller - it may be more performant to set a chunk size of 1 second and test this. 

Hope some of this helps - feel free to post more on this thread with clearer analysis of the output. 

Cheers

Matt

**Comment by SamMcGreig** [comment]
Hi Matt,

Thanks for the quick response. I've made changes from points 1 + 2 and will tests them again this week.

Yes, I am using your bulk file. I will parse the results from channels 1-128 and see what happens to them. 

I'll let you know how the testing goes and be in touch with results.

toml file:
[caller_settings]
config_name = "dna_r9.4.1_450bps_fast"
host = "127.0.0.1"
port = 5556

[conditions]
reference = "/ReadUntil/read_until/human_genome/human.mmi"

[conditions.0]
name = "select_chr_21_22"
control = false
min_chunks = 0
max_chunks = 4
targets = ["NC_000021.9", "NC_000022.11"]
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"

**Comment by SamMcGreig** [comment]
Hi Matt,

Just updating with some results:
Control (channels 127+)
![Control](https://user-images.githubusercontent.com/17768776/80371428-d0035d80-8889-11ea-91f6-ff662db9a1b7.jpg)

Read Until (channels 1-126)
![RU](https://user-images.githubusercontent.com/17768776/80371500-e7424b00-8889-11ea-9faf-2ba3ae5e7b8a.jpg)

Looks like it's worked well for one chr22 and not as well for chr21 - but overall I think it's worked quite well. Hopefully we'll be able to begin testing on our own samples in the near future.

Any feedback/suggestions would be welcome
Sam
