### ISSUE TITLE
Question regarding PC usage

### ISSUE THREAD

**Issue by neavemj** [LooseLab/ru#41]
Hi Loose Lab, thanks for the great software!
We are currently running our MinIONs using a PC desktop (32 Gb RAM, 12 CPU cores), so pretty reasonable machine. We also have direct access from the machine to high-performance compute servers with lots of GPUs, etc. I guess my quick question is whether you think it would be worth-while me trying to get 'read until' running on the PC, maybe using 'windows subsystem for linux', or should I just bite the bullet and get a new linux box? Alternatively, is there any way I can get our HPC servers to use 'read until' to control the MinION?
Thanks again,
Matt.

**Comment by alexomics** [comment]
Hi Matt, 

> I guess my quick question is whether you think it would be worth-while me trying to get 'read until' running on the PC, maybe using 'windows subsystem for linux', or should I just bite the bullet and get a new linux box?

We haven't run read until on windows at all. It should work, but is completely untested. That being said, our approach relies on GPU basecalling, which is currently only available on linux. I don't think guppy is supported on WSL.

Regarding remote basecalling, you can specify a remote basecall server. However, network latency and the additional time to send/receive the reads may slow down read until to the point that you are missing reads (they complete before you can make a decision). 

> Alternatively, is there any way I can get our HPC servers to use 'read until' to control the MinION?

I don't think that there is a way that you can run a minion remotely from another computer.

**Comment by mattloose** [comment]
Just to add - you can run read until on a remote computer - but network latency is a real issue.

**Comment by neavemj** [comment]
Great, thanks for the replies! 
I think I might try and convince my institution to get a linux machine for the MinION. Might save me a bit of trouble ;).
Cheers,
Matt.

**Comment by neavemj** [comment]
P.S. I think I read somewhere that this works ok on the MinIT compute node. Do you think this could be a reasonable solution?
Thanks again!

**Comment by mattloose** [comment]
We’ve not had success on miniT yet. There was one tweet suggesting it worked but we were unable to verify this.
