### ISSUE TITLE
Pore is inactivated quickly 

### ISSUE THREAD

**Issue by HJTsai** [LooseLab/ru#42]
Hi,

Is this a normal situation that pore is inactivated quickly during adaptive sequencing?
![messageImage_1587966899115](https://user-images.githubusercontent.com/49969700/80340128-a8fd5980-8892-11ea-8d59-2daf1c7a246e.jpg)

Hui-Ju

**Comment by mattloose** [comment]
Hi

Yes - as described here - https://www.biorxiv.org/content/10.1101/2020.02.03.926956v2 - we expect accelerated pore blocking with read until. To see if this is “normal” can you share your read length histogram with the full range and a zoomed in version of the short peak you should be seeing from read until activity?

You should make sure you are familiar with flushing and reloading libraries to make the most of a read until experiment (as also described in our paper / protocols available on the ONT website).

Good luck!

**Comment by HJTsai** [comment]
Hi,

max_chunks=8
cosmic panel
![S__283107330](https://user-images.githubusercontent.com/49969700/80345872-70fb1400-889c-11ea-8f08-ac328218b65b.jpg)
![S__283107333](https://user-images.githubusercontent.com/49969700/80345879-75bfc800-889c-11ea-823b-8c8475406cd2.jpg)
![S__283107335](https://user-images.githubusercontent.com/49969700/80345885-78bab880-889c-11ea-88ee-dfafe30e988d.jpg)

Thank you.

Hui-Ju

**Comment by mattloose** [comment]
This looks like the expected behaviour. Most of your reads are being rejected (with the cosmic panel around 98% of your reads will be off target) - the remaining reads are accepted and the distribution is looking nice. You will find the yield on the flowcell drops as pores are blocked. This can be improved with the flush and reload as documented by in our paper and on the ONT website. Your run looks good.

Good luck.

**Comment by HJTsai** [comment]
Hi,

We did not prepare nuclease flush on this run.
Based on your past experience, whether the inactivated pore (see the attached file) could be recovered?
![S__283705346](https://user-images.githubusercontent.com/49969700/80559158-3f568a00-8a0f-11ea-9aed-41d7421639e8.jpg)

**Comment by HJTsai** [comment]
Hi Matt,

Thank you for your suggestion that flush and reload enhance the yield.
But only ~70% fastq_pass reads in our twice adaptive sequencing experiment.
What is the average percentage of fastq_pass reads in your adaptive sequencing experiment?

Hui-Ju
