### ISSUE TITLE
Problem speed of mapping

### ISSUE THREAD

**Issue by ArtemPalanaria** [LooseLab/ru#44]
Dear Matt. I tried to run Read Until, went through the testing stages (to the Testing basecalling and mapping stage, point 6). In this case, basecalling is launched on GPU (RTX 2080Ti). But the speed of mapping shows more than 1-3 seconds. What could be the problem?
thank
I did the launch from a file - an example "Testing"
I attach files
[human_chr_selection.toml.txt](https://github.com/LooseLab/ru/files/4575606/human_chr_selection.toml.txt)
[chunk_log.log](https://github.com/LooseLab/ru/files/4575582/chunk_log.log)
[ru_test.log](https://github.com/LooseLab/ru/files/4575584/ru_test.log)
[guppy_basecall_server_log-2020-05-04_15-07-45.log](https://github.com/LooseLab/ru/files/4575586/guppy_basecall_server_log-2020-05-04_15-07-45.log)

**Comment by mattloose** [comment]
Hi,

There are a lot of issues here.

The toml file you provide (human_chr_selection.toml.txt) won't pass validation as it has no targets. It isn't the one passed in the command shown in ru_test.log (that one is human_chr_selection.toml). 

The ru_test.log shows that  you actually have two targets in your toml file (further suggesting an incorrect toml file here) BUT your used toml file has 2 targets, none of which are found in the reference. 

Reads will either be always off target or not map at all. If they are not mapping (and I suspect that is the case here) you will collect more data and so your basecalling will take longer and longer.

In essence I'm not sure you have configured this experiment properly.

If you can provide further information including the source of data (are you playing back a bulkfile here or something else?) and the correct toml file we might be able to help further.

Matt

**Comment by ArtemPalanaria** [comment]
Thanks for the answer. I changed the reference and the file passed the test. After starting, it still shows a long time. To start, I used the bulk file from
http://s3.amazonaws.com/nanopore-human-wgs/bulkfile/PLSP57501_20170308_FNFAF14035_MN16458_sequencing_run_NOTT_Hum_wh1rs2_60428.fast5

Attach files.
[human_chr_selection.toml.txt](https://github.com/LooseLab/ru/files/4577079/human_chr_selection.toml.txt)
[chunk_log.log](https://github.com/LooseLab/ru/files/4577080/chunk_log.log)
[ru_test.log](https://github.com/LooseLab/ru/files/4577081/ru_test.log)
[chek_toml.txt](https://github.com/LooseLab/ru/files/4577085/chek_toml.txt)

**Comment by ArtemPalanaria** [comment]
Last time I attached the wrong file (TOML) attached ..

**Comment by mattloose** [comment]
Thanks for the update - So that is a lot slower than I would expect. 

I would check a few things here.

First - how quickly can your GPU call reads when running standalone. You may need to play with guppy parameters to tune your guppy basecaller optimally.

However, we need to see if it is GPU or CPU which is limiting here - how big is your reference file that you are mapping too? Also what sort of power is your CPU?

Have you tried the fast basecalling model instead of the high accuracy model? If you see an improvement in speed here then we can pinpoint the source of the problem a little.

Thanks

**Comment by ArtemPalanaria** [comment]
Thank. I launched it on a high accuracy model - the speed for the first 2 minutes was normal, but then again everything started to slow down to 1 second or more. I have CPU Ryzen 7 (3800X 8 core 16 treads). I use as a reference the indexed file from ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
File size (mmi) more than 7 GB. Maybe this is the case?
Thanks

**Comment by mattloose** [comment]
This doesn't really make sense then. Can you please try setting the max chunks to 8 rather than infinite and see what happens?

Also - please leave it running for more than 15 minutes and check the resulting data to see if the selection is working.

**Comment by mattloose** [comment]
Also - please can you try it with the FAST model and not the High Accuracy Model. Running on the fast model will tell us something about where the lag is.

**Comment by ArtemPalanaria** [comment]
Dear Matt. I started the process on fast and hac models with max_chunks = 8
But according to the data obtained it is clear that the fast process is going as fast as necessary, and the hac is slowing down and very much. And the results obtained are also apparently bad.
Here are the fast data
![read-length-histogram-05 05 2020, 10_55_26](https://user-images.githubusercontent.com/64794310/81046852-e761cc80-8ec1-11ea-83ec-3fcd355e4c0c.png)
[chunk_log.zip](https://github.com/LooseLab/ru/files/4579618/chunk_log.zip)
[ru_test.zip](https://github.com/LooseLab/ru/files/4579619/ru_test.zip)
[result.txt](https://github.com/LooseLab/ru/files/4579615/result.txt)
and hac data
[result.txt](https://github.com/LooseLab/ru/files/4579622/result.txt)
[chunk_log.log](https://github.com/LooseLab/ru/files/4579623/chunk_log.log)
![hac](https://user-images.githubusercontent.com/64794310/81047026-40c9fb80-8ec2-11ea-8a7b-765433ff513e.png)
[ru_test.zip](https://github.com/LooseLab/ru/files/4579625/ru_test.zip)

Thank

**Comment by mattloose** [comment]
can I check what operating system you are on? And also can you provide a metric for how quickly you can basecall standard reads on your current setup?

**Comment by tchrisboles** [comment]
![image](https://user-images.githubusercontent.com/33500125/81234940-d4392480-8fc7-11ea-8ad7-a9a391cd2bed.png)

How would I check the speed in standard basecalling? From log files? I've never looked for them - give me a hint and I dig it out.

**Comment by ArtemPalanaria** [comment]
Dear Matt. Here are the system data (Ubuntu 18.04.4 LTS
Gnome 3.28.2)
 and baseсall speed files.
[guppy.txt](https://github.com/LooseLab/ru/files/4591336/guppy.txt)
[guppy_basecaller_log-2020-05-07_10-42-57.log](https://github.com/LooseLab/ru/files/4591337/guppy_basecaller_log-2020-05-07_10-42-57.log)
Thank

**Comment by vincentmanz** [comment]
I have observed the same problem here when using the hac model in the toml file,  I obtained very slow mapping time (>1s). 
#44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020

**Comment by mattloose** [comment]
Hi All,

A quick question - could people confirm the version of guppy they are using?

Thanks.

**Comment by mattloose** [comment]
If you are on version 3.6 it may be worth trying guppy 3.4.5 - it is available from:

https://mirror.oxfordnanoportal.com/software/analysis/ont-guppy_3.4.5_linux64.tar.gz

It looks as though there is a change in guppy performance that might be negatively impacting the speed of read until.

**Comment by tchrisboles** [comment]
Hi Matt and Artem, 

I have been having problems similar to Artem and I am running:
![image](https://user-images.githubusercontent.com/33500125/81423086-f2b33300-9121-11ea-84f4-69bd11087882.png)

**Comment by tchrisboles** [comment]
Thanks Matt - will try 3.4.5 later today.

**Comment by mattloose** [comment]
HI Chris,

If you can let us know how 3.4.5 goes - the accuracy differences aren't key here but the speed is. So you should find that gives you better performance. We're really keen to resolve this ASAP!

Best

Matt

**Comment by tchrisboles** [comment]
OK, I think you guys nailed it with the guppy server version. Here's my test results.
(I downloaded and untarred ont-guppy package 3.4.5 as Matt pointed out above.)
Setup basecall server:
![image](https://user-images.githubusercontent.com/33500125/81436659-d91ce600-9137-11ea-8814-9ba8d2f4b6ed.png)
In second terminal window setup the ru_generators command:
![image](https://user-images.githubusercontent.com/33500125/81436727-f6ea4b00-9137-11ea-8c4c-8fb501d9f43e.png)
I had previously modified Matt's toml file as here:
![image](https://user-images.githubusercontent.com/33500125/81436822-18e3cd80-9138-11ea-8108-9346a6801bf0.png)
After 16 min the read distribution and mapping timing looked like this:
![image](https://user-images.githubusercontent.com/33500125/81436921-44ff4e80-9138-11ea-964c-b5ead5640c99.png)
Which is much closer to Matt's readme image than I have gotten previously. Mapping timing is still not quite as fast as Matt's. Here's a close-up of 16 minute read distribution:
![image](https://user-images.githubusercontent.com/33500125/81436988-63fde080-9138-11ea-9ea7-0fab9c804127.png)
And the summarise output:
![image](https://user-images.githubusercontent.com/33500125/81437016-71b36600-9138-11ea-8a09-6b436ad266dd.png)
The median read lengths are now showing enrichments for chr21,22. Again, not quite as good as Matt's readme, but significant.
I think what would help us all would be some additional guidance on best strategies for optimizing for guppy server settings. 

Hope this helps others who are as interested in ru as we are.

**Comment by tchrisboles** [comment]
By the way, you can see my previous results using guppy 3.5.2 in Question #39.

**Comment by mattloose** [comment]
Thanks @tchrisboles 

We're just running some equivalence tests across a few GPUs here. All our work was reported using 3.4.5 - we will investigate the issues with guppy > 3.4.5 with ONT.

**Comment by mattloose** [comment]
![signal-attachment-2020-05-08-195144_001](https://user-images.githubusercontent.com/8202484/81440110-6c214480-9167-11ea-8cc6-54bbf9d4a740.png)
So here is a comparison of a 1080 vs the GPU (GV100) in the GridION - as you can see for guppy 3.4.5 performance is roughly equivalent, but guppy 3.6 performance is not sufficient for real time calling. We suspect some underlying issue that can be resolved but for now recommend guppy 3.4.5. You can have two versions of guppy running side by side as required.

**Comment by ArtemPalanaria** [comment]
Dear Matt. I got similar results as Chris using guppy 3.4.5.
[Run.txt](https://github.com/LooseLab/ru/files/4601223/Run.txt)
![run](https://user-images.githubusercontent.com/64794310/81443004-44d57200-917d-11ea-95be-36b28dc35d6b.png)
I got similar results as Chris using guppy 3.4.5
I also wanted to know - can I use any fast files in the quality of the bulk file, or do I need to prepare them somehow?
And do not tell me an example of setting up library depletion for the human genome (for enriching the metagenome)?
Thanks for the help. I am very glad that everything worked!

**Comment by mattloose** [comment]
Hi - you have to record a bulkfile from a run - you cannot use any fast5 file.

Look under the advanced file save options.

For depletion of a human genome you just need to configure your toml file to reject anything that maps to the reference you want to get rid off. Have a look at our paper for detailsl.
