### ISSUE TITLE
Read Until on a Promethion

### ISSUE THREAD

**Issue by axgraf** [LooseLab/ru#48]
Hi Matt,
thank you for this nice peace of software. I have used your code and extened it to enable targeted enrichment from a BED file. Not perfect yet but it works! So I didn't use the generator script.  

Up to now, we have managed to run Read Until on a Minion with great results. Now we tried it on a Promethion. I have set the first channel to 1 and the last channel to 3000.  I'm using the fast basecalling model. Running it with a single worker it seems not to catch up with the guppy basecaller, so we increased the workers (to 6), which seems to be able to handle the number of reads:

`2020-05-12 15:42:38,611 [read_until_lafuga] Thread:6	  **21 reads/0.28550s**	Unblocked: 1565 	Target: 398	Total reads: 4682	Guppy queue: 11
2020-05-12 15:42:38,612 [read_until_lafuga] Thread:3	**1 reads/0.09670s**	Unblocked: 1667 	Target: 460	Total reads: 4889	Guppy queue: 11
Throttle: 0.0032995089422911406
2020-05-12 15:42:38,647 [read_until_lafuga] Thread:2	**5 reads/0.13400s**	Unblocked: 1591 	Target: 426	Total reads: 4845	Guppy queue: 0
Throttle: 0.09994410490617156
2020-05-12 15:42:38,669 [read_until_lafuga] Thread:1	**2 reads/0.13900s**	Unblocked: 1529 	Target: 431	Total reads: 4708	Guppy queue: 4
2020-05-12 15:42:38,722 [read_until_lafuga] Thread:4	**1 reads/0.10409s**	Unblocked: 1688 	Target: 469	Total reads: 5077	Guppy queue: 6
Throttle: 0.09996974118985236
2020-05-12 15:42:38,866 [read_until_lafuga] Thread:3	**5 reads/0.14211s**	Unblocked: 1668 	Target: 460	Total reads: 4894	Guppy queue: 1

But Minknow only partially shows some unblocking or some kind of unblocking waves over the flowcell. 
My assumption is that the basecalling and unblocking decisions are fast enough but that the Minkow RPC port can't handle the unblocking actions in time!? Do you have any experience/advices? 

Have you ever tried to run RU on a promethION or do you have any advices what we could do? Or is it currently not possible to run it on a promethION?

Thank you for your help
Best Alex

**Comment by mattloose** [comment]
HI Alex,

Currently it's not possible to run on PromethION. We do mention this in our preprint I think. We don't advise that you run on PromethION at present until such a time as ONT provide some deeper fixes about this.

Cheers

Matt

**Comment by mattloose** [comment]
I've just checked the preprint and we do say it should "in principle" scale to the promethION - and that does hold true - but I'd wait for further news before trying this out on that platform.

**Comment by axgraf** [comment]
Hi Matt, 
thank you for the quick reply. So we will not further try to get that running and wait for further updates!
Best Alex

**Comment by hasindu2008** [comment]
Is readfish going to support the PromethION soon? Currently, is it limited by the compute-power of the GPUs on the PromethION or is it a limitation of the read until API?

**Comment by mattloose** [comment]
Hi - the limitation is neither of these. Its more fundamental to the platform and is being worked on by ont. I’d keep an eye on announcements from ONT about this.
