### ISSUE TITLE
Use of multiple refs for Read Until for low input enrichment

### ISSUE THREAD

**Issue by tchrisboles** [LooseLab/ru#49]
In your paper you described how to use read until to enrich low input library fractions for metagenomic experiments. How do you set up the references for this kind of experiment?

**Comment by mattloose** [comment]
Hi Chris,

We do a couple of different types of experiment here - one assumes knowledge of the input material - for this you simply make a reference containing all the sequences you wish to either include or exclude and compile a toml file accordingly - so lets say you have one species you wish to reject, define the whole of it's genome as a target and specify anything that matches to it to be rejected.

We have a second method - iteralign - which will fetch references from a database as it identifies them. This used centrifuge to identify reads and then grab the appropriate reference genomes.

Which sort of approach are you after?

Best

Matt

**Comment by tchrisboles** [comment]
I am making low input Rapid libraries using a phage lambda or T4 carrier DNA. The low input library is sometimes a human whole genome library. Sometimes it is a long human CATCH fragment (~1Mb). 

I was think that to reject the off targets it might be more efficient to have mapping against both lambda and human references. This assumes that if an off-target sequence is mapped it can be rejected more quckly/efficiently - is that reasonable?

If this is a viable approach, I don't  know how to set up such .mmi files. For instance, do I add a "chrL" to the hg38 ref fasta and make the minimap2 index from my "new" hybrid ref fasta?

**Comment by mattloose** [comment]
To build your own reference, just cat together the two reference fastas and then build an mmi using the -d flag in minimap2 (see https://github.com/lh3/minimap2 documentation).

I think this should work. If you want to paste your toml file here once you've made it I'd be happy to look and see if it does what I think it should! It depends a little on the strategy you choose.

**Comment by tchrisboles** [comment]
Got it - thanks.
