### ISSUE TITLE
The percentage of fastq_fail is higher than without ru_generators 

### ISSUE THREAD

**Issue by HJTsai** [LooseLab/ru#52]
Hi,

We have three ru_generators data, the percentages of fastq_fail are 31%, 39% and 38% respectively.
Whether the percentage of fastq_fail is also high in your result?
What 's your version of R9.4.1 flowcell? revC or revD?
Thanks

Amber

**Comment by mattloose** [comment]
Hi Amber,

This is a difficult question to answer - when you are rejecting reads you will end up with more shorter reads, but they shouldn't be failing reads. 

![image](https://user-images.githubusercontent.com/8202484/82908805-677acf80-9f60-11ea-890f-2730af705521.png)

This is an image from a recent run we did - 9.41% reads fail - it's around 15.5% by bases.

I wouldn't expect there to be a significant shift in pass fail ratios here.

We are running R9.4.1 and these are the latest revisions - so revD I guess.

Hope this helps,

Matt

**Comment by HJTsai** [comment]
Hi Matt,

Thank you for your response.
We want to check whether the guppy version is same as you?
MinKNOW: 3.2.10
Ru_generator: 3.4.5
Thanks.

Amber

**Comment by mattloose** [comment]
MinKNOW 3.2.10 and RU_generator 3.4.5 - same set up as you.

Matt

**Comment by mattloose** [comment]
An update on another run (both these runs are human samples) - we are looking at around 13% fail reads (by bases).

Hope this helps.

**Comment by HJTsai** [comment]
Hi Matt, 

We use NB4 cells for COSMIC 717 genes panel.
MinKNOW: 3.2.10
Ru_generator: 3.4.5 (fast model, max_chunks=8)
Sequencing was generated 7.7 Gb (4.6 Gb within 17h + 3.1 Gb after nuclease flush and reload).
The percentages of fastq_fail was 38%.
The mean coverage was 12.39x (2.47x~48.53x).
Proportion of read fragments processed in a given number of chunks was listed.
1 | 0.116449
2 | 0.580762
3 | 0.737494
4 | 0.80818
5 | 0.840069
6 | 0.859426
7 | 0.873592
8+exceeded_max_chunk | 1

Amber

**Comment by mattloose** [comment]
Hi Amber,

Cool!

So the data I showed above is also the NB4 cell line. 
![image](https://user-images.githubusercontent.com/8202484/83123433-ccebcf00-a0cc-11ea-9fda-a8337b0dcccb.png)
The plot above shows coverage over time - and we hit just over 16 Gb. We reloaded this twice, but obtained just over 7Gb in our first 21 hours of sequencing. 

The differences we are seeing here will be flowcell and library related. How much library did you load at each time?

Best

Matt

**Comment by HJTsai** [comment]
Hi Matt,

At first we load 882 ng library. 
After nuclease flush, we reload 588 ng library form same library preparation.

Amber

**Comment by HJTsai** [comment]
Hi Matt,

We want to check protocol with you.
How many nanogram of DNA for library preparation in your experiments?
When is the best time to do nuclease flush?

Amber

**Comment by mattloose** [comment]
Hi Amber,

Loading amounts depends on read lengths - for our experiments we load around 600 ng of a library with.a mean of around 8-10 kb. We nuclease flush once every 24 hours or so. With these runs we would expect to see at least 20 Gb without read until - if not more with flushing.

Just to check, what platform are you running on here? Are you using GridION?
 Matt

**Comment by HJTsai** [comment]
Hi Matt,

We use GridION for sequencing.
We input 2000 ng DNA with a mean of around 6-8 kb for library preparation and then separate two parts for loading.

 Amber
