### ISSUE TITLE
Cant simulate

### ISSUE THREAD

**Issue by JonathanCSmith** [LooseLab/ru#54]
Hi, I am trying to get this up and running in a similar deployment as the one suggested in the gridion issue, but I am immediately hitting my head against being able to simulate. MinKNOW seems to accept the modified script but I am not seeing any reads in the run (FYI I am on windows). 

Additionally, is there anyway to install the read until api v2 in a location where minknow is either not installed (I can copy over the files manually) or not installed in a default location.

Cheers!

**Comment by JonathanCSmith** [comment]
Regarding the copy directive for the minknow dependencies, I just installed everything on a temporary image and ripped out the rpc folder to copy to our cluster. 

Cheers!

**Comment by mattloose** [comment]
Sorry for the delay - I see you have made everything work which is great.

I'd be interested in knowing the performance from your cluster - we have encountered netwokr issues at various times.
